# Travis CI configuration file

sudo: false

language: c

# Install autopoint on Ubuntu (needed for gettext)
addons:
  apt:
    packages:
    - autopoint

script:
  # Ensure brew gettext is in the PATH so autopoint is found on OS X
  - PATH="$PATH:/usr/local/opt/gettext/bin" autoreconf -sivf
  - ./configure --prefix="${HOME}"
  - make
  - make check
  - make install

compiler:
  - clang
  - gcc

os:
  - linux
  - osx
