# Travis CI configuration file

sudo: false

language: c

# Install autopoint on Ubuntu (needed for gettext)
addons:
  apt:
    packages:
    - autopoint

env:
  matrix:
    - CONFIG=normal
    - CONFIG=c90
    - CONFIG=stackprotect
  global:
    - MAKEFLAGS='-j 2'

script:
  # Ensure brew gettext is in the PATH so autopoint is found on OS X
  - PATH="$PATH:/usr/local/opt/gettext/bin" autoreconf -sivf
  - if [ "$CONFIG" = "normal" ] ; then CFLAGS='-Wall -Wextra -O3'; fi
  - if [ "$CONFIG" = "c90" ] ; then CFLAGS='-std=iso9899:1990 -D_XOPEN_SOURCE=500 -Wall -Wextra -O3'; fi
  - if [ "$CONFIG" = "stackprotect" ] ; then CFLAGS='-g -O0 -fstack-protector-all'; fi
  - ./configure --prefix="${HOME}" CFLAGS="$CFLAGS" || { tail -300 config.log; false; }
  - make
  - make check
  - make install

compiler:
  - clang
  - gcc

os:
  - linux
  - osx
